repos:
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black
      language_version: python3
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.28.0
  hooks:
    - id: commitizen

ci:
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
  autoupdate_schedule: 'quarterly'
  skip: [commitizen]
