repos:
- repo: https://github.com/hadialqattan/pycln
  rev: master
  hooks:
    - id: pycln
      name: pycln
      language_version: python3
      description: "A formatter for finding and removing unused import statements."
      entry: pycln
      language: python
      types: [python]
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black
      language_version: python3
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.28.0
  hooks:
    - id: commitizen

ci:
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
  autoupdate_schedule: 'quarterly'
  skip: [commitizen]
