# not used no ? can be removed no ?

[global]
  sendAnonymousUsage = false

[log]
  level = "DEBUG"
  format = "common"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = true
    swarmMode = false

[api]
  dashboard = true
  debug = false
  insecure = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.dash]
    address = ":9000"
